import 'package:flutter/material.dart';

class District {
  final String title;

  District(this.title);
}

final List<District> district = <District>[
  District('B.baria'),
  District('Bandarban'),
  District('Bagerhat'),
  District('Barguna'),
  District('Barishal'),
  District('Bhola'),
  District('Bogura'),
  District('C. nawabganj'),
  District('Chandpur'),
  District('Chattogram'),
  District("Cox's bazar"),
  District("Cumilla"),
  District("Chuadanga"),
  District("Dhaka"),
  District("Dinajpur"),
  District("Faridpur"),
  District("Feni"),
  District("Gaibandha"),
  District("Gazipur"),
  District("Gopalganj"),
  District("Habiganj"),
  District("Jashore"),
  District("Jamalpur"),
  District('Jhalokathi'),
  District('Jhenaidah'),
  District('Joypurhat'),
  District('Khagrachari'),
  District('Kishoreganj'),
  District('Khulna'),
  District('Kurigram'),
  District('Kushtia'),
  District('Lalmonirhat'),
  District('Laxmipur'),
  District('Madaripur'),
  District('Magura'),
  District('Manikganj'),
  District('Meherpur'),
  District('Moulvibazar'),
  District('Munshiganj'),
  District('Mymensingh'),
  District('Naogaon'),
  District('Natore'),
  District('Narayanganj'),
  District('Narail'),
  District('Narshingdi'),
  District('Netrokona'),
  District('Nilphamari'),
  District('Noakhali'),
  District('Pabna'),
  District('Panchagarh'),
  District('Patuakhali'),
  District('Pirojpur'),
  District('Rajshahi'),
  District('Rajbari'),
  District('Rangamati'),
  District('Rangpur'),
  District('Satkhira'),
  District('Shariatpur'),
  District('Sherpur'),
  District('Sirajganj'),
  District('Sunamganj'),
  District('Sylhet'),
  District('Tangail'),
  District('Thakurgaon'),
];